name: Browser Agent CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  size-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ubuntu:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Container
        run: apt update && apt install -y git
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm ci
      - name: Running Prod Build
        run: npm run cdn:build:dev
      - name: Generating Asset Size Report
        run: node ./tools/scripts/diff-sizes.mjs -o build
      - name: Creating PR Comment
        run: |
          node ./tools/scripts/comment-pr.mjs \
            --pull-request=${{ github.event.pull_request.number }} \
            --token=${{ secrets.GITHUB_TOKEN }} \
            --input=./build/size_report.md \
            --tag='<!-- browser_agent asset size report -->'

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ubuntu:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Container
        run: apt update && apt install -y git
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting
        run: npm run lint

  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ubuntu:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Container
        run: apt update && apt install -y git
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run unit -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  jil-smoke-chrome:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ubuntu:latest
      options: --network-alias=bam-test-1.nr-local.net
    defaults:
      run:
        shell: bash
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: --shm-size=4g
    steps:
      - name: Setup Container
        run: apt update && apt install -y git
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm ci
      - name: Build Agent
        run: npm run build:all
      - name: Run JIL Unit Tests
        run: node ./tools/jil/bin/cli.js -f merged -b chrome@latest/linux -t 85000 --no-retry --selenium-server=selenium:4444 --unit-only

  jil-smoke-firefox:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ubuntu:latest
      options: --network-alias=bam-test-1.nr-local.net
    defaults:
      run:
        shell: bash
    services:
      selenium:
        image: selenium/standalone-firefox
        ports:
          - 4444:4444
        options: --shm-size=4g
    steps:
      - name: Setup Container
        run: apt update && apt install -y git
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm ci
      - name: Build Agent
        run: npm run build:all
      - name: Run JIL Unit Tests
        run: node ./tools/jil/bin/cli.js -f merged -b firefox@latest/linux -t 85000 --no-retry --selenium-server=selenium:4444 --unit-only
